### ISSUE TITLE
clipcatd ignores images

### ISSUE THREAD

**Issue by strafer** [xrelkd/clipcat#100]
There is a "Copy/Paste Image" item in the features in readme, and other issues mention image manipulation, so I tried to put an image in the clipboard using two methods
- `flameshot`
- `import -frame -quality 9 png:- | xclip -selection clipboard -t image/png`

In both cases, the image clearly gets into the buffer (I can paste it into gimp for example), but the `clipcatctl list` does not show corresponding element and there are no messages at all in the clipcatd log (DEBUG level is enabled) when taking an image to the buffer. Taking the text before and after taking the image works fine.

Do I misunderstand the logic of working with images, or is there some kind of bug?

I use version `0.7.0`

**Comment by xrelkd** [comment]
That might be a bug when pasting an image from `xclip` and `clipcat` fails to capture the image. Let me investigate it.

BTW, could you copy the image from a browser such as `Firefox`? `clipcatctl list` shows something like 
```
d15fa449e3c41c71: [image/png 36 KiB 2023-11-29T01:16:57.001365993Z]
```
when capturing an image.

**Comment by xrelkd** [comment]
This is a fix for current issue. https://github.com/xrelkd/clipcat/issues/100
Please give it a try, thank you! @strafer

**Comment by xrelkd** [comment]
Hi @strafer.
Clipcat `0.7.1` is released.
https://github.com/xrelkd/clipcat/releases/tag/v0.7.1 
Hope it can help you!

**Comment by realyukii** [comment]
have same issue on latest version of clipcat, I have check the image size is smaller than the limit but it still not listed in the history, did the bug come back? I have no issue with text, only history image functionality isn't working as expected

```
[hemlo@zero clipcat]$  clipcatctl version
clipcatctl 0.19.0
branch:
commit_hash:
build_time:2024-10-26 19:41:57 +00:00
build_env:rustc 1.82.0 (f6e511eec 2024-10-15) (Arch Linux rust 1:1.82.0-2),
Client Version: 0.19.0
Server Version: 0.19.0
[hemlo@zero clipcat]$  cat clipcat
clipcatctl.toml    clipcatd.toml      clipcat-menu.toml
[hemlo@zero clipcat]$  cat clipcatd.toml
daemonize = true
pid_file = "/run/user/1000/clipcatd.pid"
primary_threshold_ms = 5000
max_history = 50
synchronize_selection_with_clipboard = true
history_file_path = "/home/reyuki/.cache/clipcat/clipcatd-history"
snippets = []

[log]
emit_journald = true
emit_stdout = false
emit_stderr = false
level = "INFO"

[watcher]
enable_clipboard = true
enable_primary = true
enable_secondary = false
sensitive_x11_atoms = ["x-kde-passwordManagerHint"]
filter_text_min_length = 1
filter_text_max_length = 20000000
denied_text_regex_patterns = []
capture_image = true
filter_image_max_size = 5242880

[grpc]
enable_http = true
enable_local_socket = true
host = "127.0.0.1"
port = 45045
local_socket = "/run/user/1000/clipcat/grpc.sock"

[dbus]
enable = true

[metrics]
enable = true
host = "127.0.0.1"
port = 45047

[desktop_notification]
enable = true
icon = "accessories-clipboard"
timeout_ms = 2000
long_plaintext_length = 2000
[hemlo@zero clipcat]$ pwd
/home/reyuki/.config/clipcat
```

I'm not using particular desktop environment, just a wm, dwm

**Comment by realyukii** [comment]
oh wait, nevermind, it actually works on selection screenshot (not full screenshot)

does it mean the limit file size isn't applied?  I'm not sure

also, is there a way to make watch behaviour to only track real copy, because when I right click on selected text from terminal or doing some input, sometimes it automatically inserted into history (even when I don't copy explicitly, CTRL-C)
