### ISSUE TITLE
Load image into clipboard via clipcatctl

### ISSUE THREAD

**Issue by benedikt-bartscher** [xrelkd/clipcat#133]
Hey @xrelkd thanks for this awesome clipboard manager, I love it!
I can load images into my clipboard with `cat image.png | xclip -se c -t image/png` and clipcatctl can list and promote them just fine. However if i try to load an image with clipcatctl via `clipcatctl load -f image.png` clipcat complains about non-utf8 input:
`Error: Could not read from stdin, error: stream did not contain valid UTF-8`

Am I missing something, or is there currently no way of loading images? I would really like to fully switch to clipcat :)

**Comment by xrelkd** [comment]
Hi @benedikt-bartscher 
```shell
$ clipcatctl load --help
Loads file into clipboard

Usage: clipcatctl load [OPTIONS]

Options:
  -k, --kind <KIND>       Specify which clipboard to insert ("clipboard", "primary", "secondary") [default: clipboard]
  -m, --mime <MIME>       Specify the MIME type of the content [default: "text/plain; charset=utf-8"]
  -f, --file <FILE_PATH>
  -h, --help              Print help
```
Please use `--mime image/png` to specify the MIME type of your file.
For example:
```
$ clipcatctl load -f image.jpeg --mime image/jpeg
$ clipcatctl load -f image.png --mime image/png
$ cat image.png | clipcatctl load --mime image/png   # load file content from stdin
```

**Comment by benedikt-bartscher** [comment]
I am stupid, i used the wrong version of clipcatctl on one of my machines. Thank you very much for your detailed answer. It works fine :)
