### ISSUE TITLE
systemd service

### ISSUE THREAD

**Issue by Icelk** [xrelkd/clipcat#18]
I think we should include a systemd service and install it in the `.config/systemd/user` directory.

What are your thoughts? I have some experience in systemd services.

**Comment by Icelk** [comment]
I've made a fork which fixes this problem.
https://github.com/Icelk/clipcat

**Comment by xrelkd** [comment]
Thank you.
Starting `clipcat` with the `systemd` is a good idea. 
Maybe we can put the `systemd` unit example snippet in the `Integration` section of `README.md`.

**Comment by xrelkd** [comment]
Resolved by https://github.com/xrelkd/clipcat/pull/172.
