### ISSUE TITLE
Handling loosing connection to xclipboard

### ISSUE THREAD

**Issue by Icelk** [xrelkd/clipcat#19]
When I restart my WM, `clipcat` stops working; printing an error saying the clipboard disconnected. Then, the daemon continues to run, but without working.

I think we should make the program exit with a non-zero exit code when this error occurs. I can write the PR. Then my `systemd` unit can restart after a crash.

Or we could change it to try to reconnect to `xclipboard` when this happens.

**Comment by xrelkd** [comment]
Please try to use a newer version of `clipcat`. https://github.com/xrelkd/clipcat/releases/tag/v0.8.0
The problem might be solved by the new implementation.
