### ISSUE TITLE
paste to both PRIMARY and CLIPBOARD at the same time?

### ISSUE THREAD

**Issue by jonaz** [xrelkd/clipcat#21]
I would be nice if `clipcat-menu -f rofi` would be able to pase into both PRIMARY and CLIPBOARD at the same time?

My normal workflow is that i cannot access CLIPBOARD inside the terminal (i3 with urxvt) but only the PRIMARY one.

**Comment by xrelkd** [comment]
The following command might solve your problem:
```
$ clipcat-menu --finder rofi insert --kind primary
```
You could use `insert` command and specify `clipboard` or `primary`.

**Comment by xrelkd** [comment]
A new option `--kinds` is added in PR #119 .
The following command might solve your problem, it can insert the selected clip into both `PRIMARY` and `CLIPBOARD`:
```
$ clipcat-menu --finder rofi insert --kinds primary --kinds clipboard
```
