### ISSUE TITLE
Support snippets under a folder

### ISSUE THREAD

**Issue by jemyzhang** [xrelkd/clipcat#227]
Currently, snippets have to be configured one by one in clipcatd.toml. Is there any way we could configure a folder path to load all the snippets on startup? Furthermore, is it possible to monitor and automatically reload the files upon modifications, deletions, or additions?

**Comment by xrelkd** [comment]
Hi @jemyzhang,
Thanks for the idea.
The feature will be implemented in the near future.
Related issue: https://github.com/xrelkd/clipcat/issues/228

**Comment by xrelkd** [comment]
Resolved by #229 .
