### ISSUE TITLE
Storing date+time of each stored clip

### ISSUE THREAD

**Issue by edi9999** [xrelkd/clipcat#23]
It could be useful to store the datetime of each stored clipboard entry, so that one can after that search per date for example or see at a glance which entries are from the last hour.

This could then also be shown in the clipcat-menu command

**Comment by Icelk** [comment]
I believe the date is already saved.
https://github.com/xrelkd/clipcat/blob/21b1192213741a42f5a79d00eeb382c323f54ee7/src/lib.rs#L79
The only thing is accessing it through clipcat-menu.

**Comment by edi9999** [comment]
Oh, ok its already stored. If I have some time in the future I will take a look at the code.
Do you have any hints of which files should be changed ?

**Comment by Icelk** [comment]
I presume the code in `bin/clipcat-menu/` needs to output the date to the finder (how do we do this?). It should have access to the object, `ClipboardData`, which contains the date.

**Comment by xrelkd** [comment]
Clipcat stores the timestamp of each clip.

**Comment by realyukii** [comment]
does `clipcat-menu` have an option to show it? so far, the only entry that show timestamp is only images
