### ISSUE TITLE
"Maximum number of clients reached"

### ISSUE THREAD

**Issue by CyberShadow** [xrelkd/clipcat#24]
To reproduce:

1. Start `clipcatd`
2. Run: `while true ; do clipcatctl insert "$RANDOM" ; done`

Outcome: after a while, clipcat stops inserting new entries.

If `clipcatd` is run with `--no-daemon`, it starts printing "Maximum number of clients reached" (with no newline) instead of e.g. `INFO Clipboard ["21425"]`.

**Comment by Icelk** [comment]
Can confirm.

But that's weird. When i `grep` on my system (with all deps of clipcat in the cargo repo), I get no results.
It's nowhere in the clipcat codebase. Probably some dependency?
Then again, I should've found it.

**Comment by Icelk** [comment]
It seems to recover when I stop spamming it. Perhaps something with clipcat's gRPC implementation, which defaults to say 32 max concurrent clients?

**Comment by CyberShadow** [comment]
> But that's weird. When i `grep` on my system (with all deps of clipcat in the cargo repo), I get no results.
> It's nowhere in the clipcat codebase. Probably some dependency?
> Then again, I should've found it.

It's coming from the X server. The error message might be in a C library that clipcat is linking against, such as xlib / libxcb.

**Comment by Icelk** [comment]
Why would clipcatd initiate multiple connections to X? Form my experience (not much) clipcatd creates a connection at start, and keeps it.

**Comment by xrelkd** [comment]
Please try to use a newer version of `clipcat`. https://github.com/xrelkd/clipcat/releases/tag/v0.9.0
The problem might be solved by the new implementation.
