### ISSUE TITLE
selection indicator disappears immediately in urxvt

### ISSUE THREAD

**Issue by zaza42** [xrelkd/clipcat#267]
When I select some text in rxvt, the selection disappears immediately.  I mean the reversed colour which indicates what I selected.
It will stay on screen when using Alacritty or xterm, so it's something rxvt specific. Is it rxvt related or clipcat does something special?

Ok, it's not so annoying, just a question.

**Comment by xrelkd** [comment]
I could not reproduce this problem on `Rxvt v2.7.10 - released: 26 MARCH 2003`.

**Comment by zaza42** [comment]
I'm sorry. Not that rxvt, i'm using [rxvt-unicode](http://software.schmorp.de/pkg/rxvt-unicode.html) [9.31](http://dist.schmorp.de/rxvt-unicode/rxvt-unicode-9.31.tar.bz2).

**Comment by xrelkd** [comment]
I could not reproduce the problem on 
```
rxvt-unicode (urxvt) v9.31 - released: 2023-01-02
options: perl,xft,styles,combining,blink,iso14755,unicode3,encodings=eu+vn+jp+jp-ext+kr+zh+zh-ext,fade,transparent,tint,pixbuf,XIM,frills,selectionscrolling,wheel,slipwheel,cursorBlink,pointerBlank,scrollbars=plain+rxvt+NeXT+xterm
```
either.
Primary clipboard and selection clipboard worked, the selection on text never disappeared.

**Comment by zaza42** [comment]
Oh, I've found it. I set
`synchronize_selection_with_clipboard = false`
then the selection stays in inverse coloured even after releasing left mouse button.

I still don't understand how the selection in xterm and alacritty stays there, and I don't even understand what this option has changed. May I close this issue?

**Comment by xrelkd** [comment]
@zaza42 
Yes, please close this issue.

**Comment by zaza42** [comment]
Sorry to bother you.
