### ISSUE TITLE
Cannot run clipcat-menu

### ISSUE THREAD

**Issue by Hate9** [xrelkd/clipcat#27]
Whenever I try to run clipcat-menu, I get an error saying `Error: RunFinder: Could not spawn external process, error: No such file or directory (os error 2)`

**Comment by xrelkd** [comment]
`clipcat-menu` calls external finder such as `rofi`, `dmenu`, `fzf`, `skim`, if it can not execute the program, it throws error message.
If you do not specify the external program with `--finder`, `clipcat-menu` calls external program set in `~/.config/clipcat-menu.toml`.
