### ISSUE TITLE
[Build] Add binary releases for platform "linux/arm64" (ABI: "aarch64")

### ISSUE THREAD

**Issue by nifr** [xrelkd/clipcat#278]
First of all: THANKS for this great open-source project ❤️ 

I took it for a spin today. Awesome tool 🤩 

Could you please add binary releases for platform `linux/arm64`?

These binaries are required for use with:
* Docker Images on Apple M1/M2/M3 hardware
* IOT Devices like Raspberry Pi Zero 2 / Pi 3 / Pi 4 / Pi 5
* Cloud VMs (Ampere) like AWS Graviton / Hetzner CAX-Series

**Comment by xrelkd** [comment]
@nifr 
Pre-built executable of `clipcat v0.16.3` for `linux/arm64` is available here: https://github.com/xrelkd/clipcat/releases/tag/v0.16.3-arm64.
Please give it a try.
The arm64 executable will be available on next release.

**Comment by xrelkd** [comment]
Pre-built executable for linux/arm64 is available here:
https://github.com/xrelkd/clipcat/releases/download/v0.16.4/clipcat-v0.16.4-aarch64-unknown-linux-musl.tar.gz
