### ISSUE TITLE
"clipcat-menu edit" doesn't open editor in i3

### ISSUE THREAD

**Issue by LRitzdorf** [xrelkd/clipcat#29]
I've added a custom i3 keybind (`bindsym $mod+Shift+p exec clipcat-menu edit --editor nvim`) to launch the Clipcat editor interface. When I trigger this keybind, rofi (my chosen launcher) appears, but doesn't open Neovim when an item is selected. However, this same command does work properly from my terminal.

It would appear that some piece of the desktop environment isn't being picked up, and as a result, Neovim doesn't know how to start properly. This is just a guess, though. I'd be happy to provide logs, if that would help with troubleshooting.

**Comment by xrelkd** [comment]
Please start `nvim` in a terminal emulator, `nvim` needs a terminal to display itself.
Or you could use a graphic editor such as `gedit` to edit the clip.
```
clipcat-menu edit --editor=gedit
```

**Comment by LRitzdorf** [comment]
Aha, that would explain it. Thanks for the response!

For any future googlers: I solved this by adding the helper script below to my $PATH, and changing my i3 bind to `bindsym $mod+Shift+p exec clipcat-menu edit --editor=nvim-hosted`.
```sh
#!/bin/sh
# Neovim needs a terminal to display itself, and thus can't be started directly
# by, for example, a keybind in i3. This script simply launches a terminal to
# contain a Neovim instance.

nvim_host=kitty
exec "$nvim_host" nvim $@
```

**Comment by xrelkd** [comment]
Good to know that!
Thank you for the helper script!
Hope `clipcat` can help you.
