### ISSUE TITLE
`DBus` interface support

### ISSUE THREAD

**Issue by zefr0x** [xrelkd/clipcat#30]
Clipboard manager like [Klipper](https://userbase.kde.org/Klipper) do provide a [DBus](https://www.freedesktop.org/wiki/Software/dbus/) interface. I think it's a great feture to have. It might be optional if some one don't want to use it.

For now it's not very importent thing, but I think that it will be usefull in the future of the linux desktop as we are having flatpak and desktop portals progressing.
I don't have experiance with the freedesktop organization, but it would be greate if a new XDG Specification was made for that.

**Comment by xrelkd** [comment]
Resolved by #208 .
