### ISSUE TITLE
clipcatd does not restart

### ISSUE THREAD

**Issue by shyguyCreate** [xrelkd/clipcat#336]
I am using LightDM and starting clipcat in ~/.xprofile and ~/.xinitrc with `clipcatd &`. I have also tried with adding `--replace` and `--no-daemon` but that does not make a difference.

Clipcat starts without a problem in the first login, but when changing to a different tty and running `sudo systemctl stop lightdm.service`, clipcatd is stopped, and then doing `startx`; clipcat does not start. And it throws the error when trying to run it manually.

```
Error: Could not call gRPC client, error: Error occurs while connecting to Clipcat Server gRPC endpoint `/run/user/1000/clipcat/grpc.sock` via local socket, error: transport error
```

I am thinking the problem is in `/run/user/1000/clipcatd.pid` that keeps hanging after clipcatd was stopped in lightdm.

Using `journalctl --file /var/log/journal/26f884b489564e6388bf2ed2f35c4d3d/user-1000.journal | grep clipcat` I can see the following error:

```
clipcatd[1460]: Another instance (PID: 1433) is running, please terminate `1433` first
```

And running `cat /run/user/1000/clipcatd.pid`, I get that same ID. `1433`

The problem seems to be that clipcatd does not modify the `clipcatd.pid` file with a new ID even though there is no clipcatd process running.

**Comment by xrelkd** [comment]
Do you have similar log messages like these?
```
Feb 25 03:35:03 localhost clipcatd[5232]: clipcatd is shutdown
Feb 25 03:35:03 localhost clipcatd[5232]: Remove PID file `/run/user/1000/clipcatd.pid`
Feb 25 03:35:03 localhost clipcatd[5232]: Clipboard worker is shut down gracefully
..............
Feb 25 03:35:02 localhost clipcatd[5232]: Listener is about to quit, no need to re-connect to X11 server (clipboard kind: Clipboard)
Feb 25 03:35:02 localhost clipcatd[5232]: Desktop notification worker is shut down gracefully
Feb 25 03:35:02 localhost clipcatd[5232]: Could not send desktop notification, error: I/O error: Connection reset by peer (os error 104)
Feb 25 03:35:02 localhost clipcatd[5232]: Reap thread which listening to X11 server (clipboard kind: Clipboard)
Feb 25 03:35:02 localhost clipcatd[5232]: Clips are stored in `/home/user/.cache/clipcat/clipcatd-history`
Feb 25 03:35:02 localhost clipcatd[5232]: Save history and shrink to capacity 200
Feb 25 03:35:02 localhost clipcatd[5232]: gRPC local socket server is shut down gracefully
Feb 25 03:35:02 localhost clipcatd[5232]: Metrics server is shut down gracefully
Feb 25 03:35:02 localhost clipcatd[5232]: gRPC HTTP server is shut down gracefully
Feb 25 03:35:02 localhost clipcatd[5232]: Remove Unix domain socket `/run/user/1000/clipcat/grpc.sock`
Feb 25 03:35:02 localhost clipcatd[5232]: Clipboard Watcher worker is shut down gracefully
Feb 25 03:35:02 localhost clipcatd[5232]: D-Bus service is shut down gracefully
Feb 25 03:35:02 localhost clipcatd[5232]: Shut down `UNIX signal listener (SIGTERM)`
Feb 25 03:35:02 localhost clipcatd[5232]: Shut down `UNIX signal listener (SIGINT)`
Feb 25 03:35:02 localhost clipcatd[5232]: Shut down `Clipboard worker`
Feb 25 03:35:02 localhost clipcatd[5232]: Shut down `Clipboard Watcher worker`
Feb 25 03:35:02 localhost clipcatd[5232]: Shut down `Metrics server`
Feb 25 03:35:02 localhost clipcatd[5232]: Shut down `gRPC local socket server`
Feb 25 03:35:02 localhost clipcatd[5232]: Shut down `gRPC HTTP server`
Feb 25 03:35:02 localhost clipcatd[5232]: Shut down `D-Bus`
Feb 25 03:35:02 localhost clipcatd[5232]: Shut down `Desktop notification worker`
Feb 25 03:35:02 localhost clipcatd[5232]: `SIGTERM` received, starting graceful shutdown
```

`clipcatd` waits for the `SIGTERM` or `SIGINT` after starting. `clipcatd` stops to conduct gracefully shutdown after receiving `SIGTERM` or `SIGINT`.
If `clipcatd` is killed by `SIGKILL`, then it does not shut down gracefully.
If `clipcatd` does not shut down gracefully, the `/run/user/1000/clipcatd.pid` is not removed.

Maybe you can use `pkill --signal SIGTERM clipcatd` to shut down `clipcatd` when you are stopping `LightDM`.

**Comment by shyguyCreate** [comment]
I am not getting any messages of clipcat shutting down, I only get this:

```
clipcatd[482]: clipcatd is initializing, pid: 482
clipcatd[482]: Initializing Tokio runtime
clipcatd[482]: Build X11 listener (Clipboard) with display `:0`
clipcatd[482]: Connecting X11 server (clipboard kind: Clipboard)
clipcatd[482]: Connected to X11 server (clipboard kind: Clipboard)
clipcatd[482]: History file path: `/home/shyguy/.cache/clipcat/clipcatd-history`
clipcatd[482]: Open `/home/shyguy/.cache/clipcat/clipcatd-history/header.json`, schema: 2, last update: 2024-02-25T22:14:58.529496951Z
clipcatd[482]: Load history from `/home/shyguy/.cache/clipcat/clipcatd-history`
clipcatd[482]: 61 clip(s) loaded
clipcatd[482]: Initialize ClipboardManager with capacity 50
clipcatd[482]: Import 61 clip(s) into ClipboardManager
clipcatd[482]: Import 0 snippet(s) into ClipboardManager
clipcatd[482]: Listen metrics endpoint on 127.0.0.1:45047
clipcatd[482]: Provide Clipcat D-Bus service at org.clipcat.clipcat
clipcatd[482]: Clipboard Watcher worker is started
clipcatd[482]: Listen Clipcat gRPC endpoint on 127.0.0.1:45045
clipcatd[482]: Listen Clipcat gRPC endpoint on /run/user/1000/clipcat/grpc.sock
clipcatd[482]: The clipboard contents were not available in the requested format or the clipboard is empty.
clipcatd[482]: The clipboard contents were not available in the requested format or the clipboard is empty.
clipcatd[482]: D-Bus service is created
clipcatd[1443]: Another instance (PID: 482) is running, please terminate `482` first
```

The last line is the one that appears when I do startx in another tty after stopping LightDM.

**Comment by xrelkd** [comment]
If you execute `$ clipcatd --replace`, it tries to kill the previous `clipcatd`. Otherwise, it does not start a new daemon.
There is no other message shows that the previous `clipcatd` is terminated, so the `clipcatd` with pid 482 may be still running.

Could you use `$ clipcatctl list` or `clipcat-menu` to list the content of clipboard entries? 
If the `clipcatd` is not running, it shows
```
Error: Could not call gRPC client, error: Error occurs while connecting to Clipcat Server gRPC endpoint `/run/user/1000/clipcat/grpc.sock` via local socket, error: transport error
``` on stdout.

**Comment by shyguyCreate** [comment]
Using `clipcatd --replace &` in ~/.xinitrc. I get the following log:

```
clipcatd[3554]: clipcatd is initializing, pid: 3554
..............
clipcatd[5486]: Try to terminate another instance (PID: 3554)
clipcatd[5486]: Error occurs while trying to terminate another instance, error: Failed to send `SIGTERM` to PID `3554`
clipcatd[5486]: PID file `/run/user/1000/clipcatd.pid` exists, another instance (PID: 3554) is still running, sleep for 200ms
clipcatd[5486]: PID file `/run/user/1000/clipcatd.pid` exists, another instance (PID: 3554) is still running, sleep for 200ms
clipcatd[5486]: PID file `/run/user/1000/clipcatd.pid` exists, another instance (PID: 3554) is still running, sleep for 200ms
..............
```

**Comment by shyguyCreate** [comment]
> Did you try to put `$ clipcatd --replace` in your `~/.xinitrc` (only use `$ clipcatd --replace` without `&`) ?
I try, and it clipcatd will run forever.

> Does clipcatd with PID `3554` show `SIGTERM received, starting graceful shutdown` in the log message?
There is no message like that in the logs. When looking for SIGTERM, I only get:

```
clipcatd[4940]: Error occurs while trying to terminate another instance, error: Failed to send `SIGTERM` to PID `3554`
clipcatd[5486]: Error occurs while trying to terminate another instance, error: Failed to send `SIGTERM` to PID `3554`
clipcatd[6576]: Error occurs while trying to terminate another instance, error: Failed to send `SIGTERM` to PID `3554`
clipcatd[6742]: Error occurs while trying to terminate another instance, error: Failed to send `SIGTERM` to PID `3554`
clipcatd[6842]: Error occurs while trying to terminate another instance, error: Failed to send `SIGTERM` to PID `3554`
```

**Comment by xrelkd** [comment]
What is the result when you executed `$ kill $(cat /run/user/1000/clipcatd.pid)`?
Is the `clipcatd` with PID in `cat /run/user/1000/clipcatd.pid` still running?
If `clipcatd` is not running but the old PID is still in `/run/user/1000/clipcatd.pid`, then the previous `clipcatd` was killed by `SIGKILL`, it had no chance to shut down gracefully.

Personally, I prefer to use `systemd` to manage the background services such as `clipcatd`, `wired-notify`, `dunst` and so on.
You can find the example for starting `clipcatd` with `systemd`.

**Comment by shyguyCreate** [comment]
> What is the result when you executed `$ kill $(cat /run/user/1000/clipcatd.pid)`? 

kill: kill 3554 failed: no such process

**Comment by shyguyCreate** [comment]
> Personally, I prefer to use `systemd` to manage the background services such as `clipcatd`, `wired-notify`, `dunst` and so on. You can find the example for starting `clipcatd` with `systemd` in the `README.md`.

I have tried that approach but `graphical-session.target` is not started by systemd, so clipcatd was never started.

**Comment by xrelkd** [comment]
> kill: kill 3554 failed: no such process

The previous `clipcatd` might be killed by `SIGKILL`, instead of `SIGINT` or `SIGTERM`, so it did not perform gracefully shutdown.
You have to remove `/run/user/1000/clipcatd.pid` and `/run/user/1000/clipcat/grpc.sock` manually, if `clipcatd` did not shut down gracefully.

> I have tried that approach but graphical-session.target is not started by systemd, so clipcatd was never started.

If you are an Arch Linux user, please try to replace `graphical-session.target` with `default.target`.

**Comment by xrelkd** [comment]
If the `graphical-session.target` of `systemd` is not available on your machine, use the following configuration.
```
[Unit]
Description=Clipcat Daemon
PartOf=default.target

[Install]
WantedBy=default.target

[Service]
# NOTE: We assume that your `clipcatd` is placed at `/usr/bin/clipcatd`.
ExecStart=/usr/bin/clipcatd --no-daemon --replace
Restart=on-failure
Type=simple
```

**Comment by shyguyCreate** [comment]
I have tried that and  get: `clipcatd[456]: Could not initialize clipboard, error: Could not create X11 connection, error: $DISPLAY variable not set and no value was provided explicitly`

**Comment by shyguyCreate** [comment]
> The previous `clipcatd` might be killed by `SIGKILL`, instead of `SIGINT` or `SIGTERM`, so it did not perform gracefully shutdown. You have to remove `/run/user/1000/clipcatd.pid` and `/run/user/1000/clipcat/grpc.sock` manually, if `clipcatd` did not shut down gracefully.

I am aware of that workaround, but `clipcatd --replace` should replace the previous PID regardless if clipcatd is running or not, right?

**Comment by xrelkd** [comment]
> I am aware of that workaround, but clipcatd --replace should replace the previous PID regardless if clipcatd is running or not, right?

To keep it safe, `clipcatd --replace` sends `SIGTERM` to another `clipcatd` instance, waiting for the previous `clipcatd` being shut down.

We have to wait for a while before `replace` the previous `clipcatd`, because the previous `clipcatd` needs time to save the state and remove the PID file before it really exited.

**Comment by shyguyCreate** [comment]
But if clipcatd sends `error: Failed to send SIGTERM to PID`, using `clipcatd --replace` should still overwrite the PID and socket file, right?

**Comment by shyguyCreate** [comment]
I understand the reason of waiting for previous clipcatd to handle the PID file, I even can see it in the logs after restarting clipcatd and the using `--replace`.

```
clipcatd[9958]: Try to terminate another instance (PID: 9911)
clipcatd[9958]: PID file `/run/user/1000/clipcatd.pid` exists, another instance (PID: 9911) is still running, sleep for 200ms
clipcatd[9911]: `SIGTERM` received, starting graceful shutdown
clipcatd[9911]: Shut down `D-Bus`
clipcatd[9911]: Shut down `gRPC HTTP server`
clipcatd[9911]: Shut down `gRPC local socket server`
clipcatd[9911]: Shut down `Metrics server`
clipcatd[9911]: Shut down `Clipboard Watcher worker`
clipcatd[9911]: Shut down `Clipboard worker`
clipcatd[9911]: Shut down `UNIX signal listener (SIGINT)`
clipcatd[9911]: D-Bus service is shut down gracefully
clipcatd[9911]: Shut down `UNIX signal listener (SIGTERM)`
clipcatd[9911]: gRPC HTTP server is shut down gracefully
clipcatd[9911]: Metrics server is shut down gracefully
clipcatd[9911]: Clipboard Watcher worker is shut down gracefully
clipcatd[9911]: Remove Unix domain socket `/run/user/1000/clipcat/grpc.sock`
clipcatd[9911]: Save history and shrink to capacity 50
clipcatd[9911]: gRPC local socket server is shut down gracefully
clipcatd[9911]: Clips are stored in `/home/shyguy/.cache/clipcat/clipcatd-history`
clipcatd[9911]: Reap thread which listening to X11 server (clipboard kind: Clipboard)
clipcatd[9911]: Clipboard worker is shut down gracefully
clipcatd[9911]: Remove PID file `/run/user/1000/clipcatd.pid`
clipcatd[9911]: clipcatd is shutdown
clipcatd[9963]: clipcatd is initializing, pid: 9963
```

I can see in there that clipcatd sends `SIGTERM received, starting graceful shutdown`. Then my question is: if clipcatd instead of sending that it sends `Error occurs while trying to terminate another instance, error: Failed to send SIGTERM to PID` shouldn't the responsibility of the PID file be given to the new daemon?

**Comment by xrelkd** [comment]
> if clipcatd instead of sending that it sends Error occurs while trying to terminate another instance, error: Failed to send SIGTERM to PID shouldn't the responsibility of the PID file be given to the new daemon?

The last step of gracefully shutdown is to remove the PID file, once the PID file is removed, the previous `clipcatd` instance is completed.
The newer `clipcatd` need to check the PID file of previous `clipcatd` instance, so that the newer one can know which PID it should use to send `SIGTERM`.

When you see `Error occurs while trying to terminate another instance, error: Failed to send SIGTERM to PID 12345`, it means the newer instance failed to perform the `int kill(pid_t pid, int sig)` syscall, the procedure is somehow conservative, `clipcatd` will not force remove the old PID file.

**Comment by shyguyCreate** [comment]
After reading some [documentation](https://www.gnu.org/software/libc/manual/html_node/Termination-Signals.html#index-SIGKILL) I get why clipcatd is failing. Since `SIGKILL` can not be handled, this means that this problem is out of scope, is that right?

**Comment by xrelkd** [comment]
> The SIGKILL signal is used to cause immediate program termination. It cannot be handled or ignored, and is therefore always fatal. It is also not possible to block this signal. 

This is the main reason we do not and we  cannot handle `SIGKILL` in most of the processes. 

Handling SIGKILL is out of the scope, that is why I emphasized you must use SIGTERM or SIGINT to stop clipcatd in the beginning.
