### ISSUE TITLE
error when not used for a long time

### ISSUE THREAD

**Issue by Syuq** [xrelkd/clipcat#467]
/usr/bin/clipcatd --no-daemon --replace
Error: Error occurs while creating Unix domain socket listener on `/run/user/1000/clipcat/grpc.sock`, error: Address already in use (os error 98)
How to fix: 
rm /run/user/1000/clipcat/grpc.sock
or:
Starting clipcatd with [systemd](https://systemd.io/)
Put the following snippet in `$XDG_CONFIG_HOME/systemd/user/clipcat.service:`
```sh
[Unit]
Description=Clipcat Daemon
PartOf=graphical-session.target

[Install]
WantedBy=graphical-session.target

[Service]
ExecStartPre=/bin/rm -f /run/user/1000/clipcat/grpc.sock
ExecStart=/usr/bin/clipcatd --no-daemon --replace
Restart=on-failure
Type=simple
```

Tks

**Comment by xrelkd** [comment]
Fixed by https://github.com/xrelkd/clipcat/issues/467, https://github.com/xrelkd/clipcat/pull/481.
