### ISSUE TITLE
Disable/enable/toggle clipcatd with clipcatctl

### ISSUE THREAD

**Issue by tdemin** [xrelkd/clipcat#6]
Sometimes, copying and pasting sensitive information (e.g. when using password managers like `pass`) is a thing, and killing/restarting `clipcatd` is not exactly the best solution for this.

clipcatctl should be able to temporarily disable/enable back clipcatd.

**Comment by xrelkd** [comment]
@tdemin Thanks for your recommendation.
I just added some new sub-commands (`enable`, `disable`, `toggle`) for controlling `clipcatd`.
